name: Java Style Checks

on:
  pull_request:
  push:

jobs:
  style:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - name: Check google-java-format
        run: mvn com.coveo:fmt-maven-plugin:2.11:check
      - name: Run Checkstyle
        run: mvn org.apache.maven.plugins:maven-checkstyle-plugin:3.2.2:check
